name: AI Code Review

on:
  pull_request:
    paths-ignore:
      - "**/*.json"
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.svg"
      - ".gitgnore"

jobs:
  code-review:
    if: github.event.pull_request.user.name != 'renovate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout
        uses: actions/checkout@v4
      # This step references the directory that contains the action.
      - name: Review
        uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          # model: 'gpt-4'
          max-length: 8000
          # prompt: 'Only suggest performance improvements for this code.'
          # post-if-error: false
