name: OpenAI Code Review

on:
  pull_request:
    paths-ignore:
      - "**/*.json"
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.svg"
      - ".gitgnore"

jobs:
  call_code_review:
    name: Call Code Review
    uses: umzug-meister/workflows/.github/workflows/ai-review.yml@main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    permissions:
      contents: read
      pull-requests: write
